cards/urls.py
# cards/urls.py

from django.urls import path

from . import views

urlpatterns = [
    path(
        "",
        views.CardListView.as_view(),
        name="card-list"
    ),
    path(
        "new",
        views.CardCreateView.as_view(),
        name="card-create"
    ),
    path(
        "edit/<int:pk>",
        views.CardUpdateView.as_view(),
        name="card-update"
    ),
    path(
        "box/<int:box_num>",
        views.BoxView.as_view(),
        name="box"
    ),
    path(
        "archive",
        views.ArchivedCardListView.as_view(),
        name="archive"
    ),
    path(
        "delete/<int:pk>",
        views.CardDeleteView.as_view(),
        name="card-delete"     
    ),
    path(
        "archive-card/<int:pk>",
        views.CardArchiveView.as_view(),
        name="card-archive"
    ),
    path(
        "restore-card/<int:pk>",
        views.CardRestoreView.as_view(),
        name="card-restore"
    ),
]

flashcards/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("cards.urls")),
]

cards/models.py
from django.db import models


NUM_BOXES = 5
BOXES = range(1, NUM_BOXES + 1)

class Card(models.Model):
    question = models.CharField(max_length=100)
    answer = models.TextField()
    box = models.IntegerField(
        choices=zip(BOXES, BOXES),
        default=BOXES[0],
    )
    date_created = models.DateTimeField(auto_now_add=True)
    archived = models.IntegerField(default=0)

    def __str__(self):
        return self.question
    
    def move(self, solved):
        new_box = self.box + 1 if solved else BOXES[0]

        if new_box in BOXES:
            self.box = new_box
            self.save()

        return self
    
    def archive(self):
        self.archived = 1
        self.save()
        return self
    
    def restore(self):
        self.archived = 0
        self.box = 1
        self.save()
        return self
    

cards/forms.py
from django import forms

class CardCheckForm(forms.Form):
    card_id = forms.IntegerField(required=True)
    solved = forms.BooleanField(required=False)
    
    
class CardArchiveForm(forms.Form):
    card_id = forms.IntegerField(required=True)
    

cards/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)

from .models import Card
from django.shortcuts import get_object_or_404, redirect
from .forms import CardCheckForm, CardArchiveForm
from django.views.generic import TemplateView

import random

class ArchivedCardListView(ListView):
    model = Card
    queryset = Card.objects.filter(archived=1)
    template_name = "cards/archived_card_list.html"

class CardListView(ListView):
    model = Card
    queryset = Card.objects.filter(archived=0)

class CardCreateView(CreateView):
    model = Card
    template_name = "cards/card_create_form.html"
    fields = ["question", "answer", "box"]
    success_url = reverse_lazy("card-create")
    
class CardUpdateView(UpdateView):
    model = Card
    template_name = "cards/card_update_form.html"
    fields = ["question", "answer", "box"]
    success_url = reverse_lazy("card-list")
    
class CardDeleteView(DeleteView):
    model = Card
    success_url = reverse_lazy("card-list")
    
class CardArchiveView(TemplateView): 
    success_url = reverse_lazy("card-list")
    model = Card
    template_name = "cards/card_archive.html"
    form_class = CardArchiveForm
    
    def post(self, request, *args, **kwargs):
        print("Before archiving")
        card = get_object_or_404(Card, id=self.kwargs["pk"])
        card.archive()
        print("After archiving")
        return redirect("card-list")
    
class CardRestoreView(TemplateView): 
    success_url = reverse_lazy("card-list")
    model = Card
    template_name = "cards/card_restore.html"
    form_class = CardArchiveForm
    
    def post(self, request, *args, **kwargs):
        print("Before restoring")
        card = get_object_or_404(Card, id=self.kwargs["pk"])
        card.restore()
        print("After restoring")
        return redirect("card-list")
        
    
    
class BoxView(CardListView):
    template_name = "cards/box.html"
    form_class = CardCheckForm

    def get_queryset(self):
        return Card.objects.filter(box=self.kwargs["box_num"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["box_number"] = self.kwargs["box_num"]
        if self.object_list:
            context["check_card"] = random.choice(self.object_list)
        return context
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            card = get_object_or_404(Card, id=form.cleaned_data["card_id"])
            card.move(form.cleaned_data["solved"])

        return redirect(request.META.get("HTTP_REFERER"))

cards/templates/cards/archived_card.html
<article>
    <h4>{{ card.question }}</h4>
    {% if not check_card %}
        <p>{{ card.answer }}</p>
        <hr>
        <a href="{% url 'card-restore' card.id %}" role="button">
            ✏️ Restore Card
        </a>
    {% else %}
        <details>
            <summary>Reveal Answer</summary>
            <p>{{ card.answer }}</p>
        </details>
        <hr>
        {% include "cards/card_check_form.html" with solved=True %}
        {% include "cards/card_check_form.html" with solved=False %}
    {% endif %}
 </article>

cards/templates/cards/archived_card_list.html
{% extends "cards/base.html" %}

{% load humanize %}

{% block content %}
    <h2>
        Archived Cards
    </h2>
    {% for card in card_list %}
        {% ifchanged %}
            <h3>🗃 {{ card.box | ordinal }} Box</h3>
        {% endifchanged %}
        {% include "cards/archived_card.html" %}
    {% endfor %}
{% endblock content %}

cards/templates/cards/base.html
<!-- cards/templates/cards/base.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Flashcards</title>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<style>
    /* Custom CSS */

    :root {
        --accent: #6e48ad;
        --accent-bg: white;
        --bg: #fff;
        --text: #212121;
        --text-light: #585858;
        --border: #d8dae1;
        --code: #d81b60;
        --preformatted: #444;
    }

    article {
        background-color: grey;
        border: 1px solid var(--border);
        border-radius: 5px;
        padding: 1em;
        margin: 1em 0;
    }

    h2 {
        text-align: center;
    }

    h2, h4 {
        margin-top: 0;
    }

    hr {
        background: var(--accent);
        border-color: var(--accent);
    }

    button,
    a[role="button"] {
        color: white;
        text-decoration: none;
    }

    input, select, textarea {
        width: 100%;
        margin-bottom: 10px;
        align-items: center;
    }
</style>

<body>
    <header>
        <h1>Flashcards App</h1>
        {% include "cards/navigation.html" %}
    </header>
    <main>
        {% block content %}
            <h2>Welcome to your Flashcards app!</h2>
        {% endblock content %}
    </main>
</body>

</html>

cards/templates/cards/box.html
{% extends "cards/base.html" %}
{% load humanize %}

{% block content %}
    <h2>🗃 {{ box_number | ordinal }} Box</h2>
    <mark>{{ object_list | length }}</mark> Card{{ object_list | pluralize }} left in box.
    <hr>
    {% if check_card %}
        {% include "cards/card.html" with card=check_card %}
    {% endif %}
{% endblock content %}

cards/templates/cards/box_links.html
{% load humanize %}

{% for box in boxes %}
    <a href="{% url 'box' box_num=box.number %}">
        🗃 {{ box.number | ordinal }} Box <mark>{{ box.card_count }}</mark>
    </a>
{% endfor %}

cards/templates/cards/card.html
<article>
    <h4>{{ card.question }}</h4>
    {% if not check_card %}
        <p>{{ card.answer }}</p>
        <hr>
        <a href="{% url 'card-update' card.id %}" role="button">
            ✏️ Edit Card
        </a>
    {% else %}
        <details>
            <summary>Reveal Answer</summary>
            <p>{{ card.answer }}</p>
        </details>
        <hr>
        {% include "cards/card_check_form.html" with solved=True %}
        {% include "cards/card_check_form.html" with solved=False %}
    {% endif %}
 </article>

cards/templates/cards/card_archive.html
{% extends "cards/base.html" %}

{% load humanize %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to archive?</p>
    {{ form }}
    <input type="submit" value="✅">
</form>
{% endblock %}

cards/templates/cards/card_check_form.html
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="card_id" value="{{ card.id }}">
    <input type="hidden" name="solved" value="{{ solved }}">
    {% if solved %}
        <input type="submit" value="✅ I know"/>
    {% else %}
        <input type="submit" value="❌ I don't know"/>
    {% endif %}
</form>

cards/templates/cards/card_confirm_delete.html
{% extends "cards/base.html" %}

{% load humanize %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="✅">
</form>
{% endblock %}

cards/templates/cards/card_create_form.html
{% extends "cards/base.html" %}

{% block content %}
    {% if card %}
    <h2>✏️ Edit Card</h2>
    {% else %}
    <h2>✨ Create New Card</h2>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save Card">
    </form>
    <a href="{% url 'card-list' %}">
        Cancel
    </a>
{% endblock %}

cards/templates/cards/card_list.html
{% extends "cards/base.html" %}

{% load humanize %}

{% block content %}
    <h2>
        All Cards
    </h2>
    <a href="{% url 'card-create' %}" role="button" style="color: black;">
        ✨ Create New Card
    </a>
    {% for card in card_list %}
        {% ifchanged %}
            <h3>🗃 {{ card.box | ordinal }} Box</h3>
        {% endifchanged %}
        {% include "cards/card.html" %}
    {% endfor %}
{% endblock content %}

cards/templates/cards/card_restore.html
{% extends "cards/base.html" %}

{% load humanize %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to restore?</p>
    {{ form }}
    <input type="submit" value="✅">
</form>
{% endblock %}

cards/templates/cards/card_update_form.html
{% extends "cards/base.html" %}

{% block content %}
    {% if card %}
    <h2>✏️ Edit Card</h2>
    {% else %}
    <h2>✨ Create New Card</h2>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save Card">
    </form>
    <a href="{% url 'card-archive' card.id %}">
        <input type="button" value="Archive"/>
    </a>
    <a href="{% url 'card-delete' card.id %}">
        <input type="button" value="Delete" style="background-color: red; border-color: red;"/>
    </a>
    <a href="{% url 'card-list' %}">
        Cancel
    </a>
{% endblock %}

cards/templates/cards/navigation.html
{% load cards_tags %}

<nav>
    <a href="{% url 'card-list' %}">🗂 All Cards</a>
    {% boxes_as_links %}
    <a href="{% url 'archive' %}"> 📇 Archive</a>
</nav>